
###################  项目启动端口  ###################
server.port: 8092

###################  url通用路径  ###################
adminPath: map-admin

manju:
  muti-datasource-open: false #是否开启多数据源(true/false)

###################  spring配置  ###################

spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    view:
      prefix: /templates

logging:
  level:
    org.springframework.web.servlet: ERROR

---

###################  mybatis-plus 配置  ###################
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  typeAliasesPackage: >
    com.manjushirwa.pojo
  global-config:
    id-type: 3 # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################


spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://120.79.72.80:3306/manju?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  level:
    ROOT: INFO
    com:
      gx: DEBUG
  file: logs/app.log


########################  dir 项目路径  ##########################
generator:
  datasourceURL: jdbc:mysql://120.79.72.80:3306/manju?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
  driverName: com.mysql.cj.jdbc.Driver
  userName: root
  password: root
  baseEntityPath: com.manjushirwa.pojo.admin.po.
  dirPath: C:/Users/ALEX/IdeaProjects/manju-platform
  entityPath: /manju-platform-common-pojo/src/main/java/com/manjushirwa/pojo/admin/po/
  mapperXmlPath: /manju-platform-common-mapper/src/main/resources/mapper/admin/
  mapperPath: /manju-platform-common-mapper/src/main/java/com/manjushirwa/mapper/admin/
  servicePath: /manju-platform-admin-service-api/src/main/java/com/manjushirwa/service/
  serviceImplPath: /manju-platform-admin-service/src/main/java/com/manjushirwa/service/impl/
  controllerPath: /manju-platform-admin-web/src/main/java/com/manjushirwa/controller/
  htmlPath: /manju-platform-admin-web/src/main/resources/templates/