
###################  项目启动端口  ###################
server.port: 8092

###################  url通用路径  ###################
adminPath: map-admin

###################  spring配置  ###################

spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    view:
      prefix: /templates

logging:
  level:
    org.springframework.web.servlet: ERROR

---

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  typeAliasesPackage: >
    com.manjushira.pojo
  global-config:
    id-type: 3 # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################

spring:
  profiles: dev
  datasource:
    url: jdbc:oracle:thin:@172.16.43.185:1521:ora11g
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: map_admin
    password: map_admin
logging:
  level:
    ROOT: INFO
    com:
      gx: DEBUG
  file: logs/app.log